---
- hosts: webserver
  become: true
  gather_facts: True
  tasks:
   - name: Copy file
     copy:
       src: /root/permission/permission.py
       dest: /root/permission.py
       mode: 0777 
   - name: Executing the PYTHON SCRIPT
     command: /root/permission.py
     register: ServerCheck
   - debug: var={{ item }}
     with_items:
       - ServerCheck.stdout
